-- Tabulka koncertů
create table concerts (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  description text,
  group_name text not null,
  price integer not null,
  image text,
  qr_code jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabulka galerie
create table gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabulka referencí
create table testimonials (
  id bigint generated by default as identity primary key,
  author text not null,
  text text not null,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);